CREATE TABLE "HERON"."DROC_REVIEWERS"
  (
    "USER_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "ORG"     VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "STATUS"  VARCHAR2(1 BYTE) NOT NULL ENABLE,
    CONSTRAINT "SPONSORS1_PK" PRIMARY KEY ("USER_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  );
  
  CREATE TABLE "HERON"."SPONSORSHIP"
  (
    "SPONSORSHIP_ID" NUMBER,
    "USER_ID"        VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "SPONSOR_ID"     VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "LAST_UPDT_TMST" DATE NOT NULL ENABLE,
    "ACCESS_TYPE"    VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "RESEARCH_TITLE" VARCHAR2(500 BYTE) NOT NULL ENABLE,
    "RESEARCH_DESC"  VARCHAR2(1000 BYTE) NOT NULL ENABLE,
    "EXPIRE_DATE" DATE,
    "KUMC_EMPL_FLAG"       VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "KUMC_APPROVAL_STATUS" VARCHAR2(1 BYTE),
    "UKP_APPROVAL_STATUS"  VARCHAR2(1 BYTE),
    "KUH_APPROVAL_STATUS"  VARCHAR2(1 BYTE),
    "KUMC_APPROVED_BY"     VARCHAR2(50 BYTE),
    "KUMC_APPROVAL_TMST" DATE,
    "UKP_APPROVED_BY" VARCHAR2(50 BYTE),
    "UKP_APPROVAL_TMST" DATE,
    "KUH_APPROVED_BY" VARCHAR2(50 BYTE),
    "KUH_APPROVAL_TMST" DATE,
    "SIGNATURE" VARCHAR2(100 BYTE),
    "SIGNED_DATE" DATE,
    CONSTRAINT "SPONSORSHIP_PK" PRIMARY KEY ("SPONSORSHIP_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "SPONSORSHIP_FK2" FOREIGN KEY ("SPONSOR_ID") REFERENCES "HERON"."SYSTEM_ACCESS_USERS" ("USER_ID") ENABLE
  );
  
  CREATE TABLE "HERON"."SYSTEM_ACCESS_USERS"
  (
    "USER_ID"        VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "USER_FULL_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "SIGNATURE"      VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "SIGNED_DATE" DATE NOT NULL ENABLE,
    "LAST_UPDT_TMST" DATE NOT NULL ENABLE,
    CONSTRAINT "SYSTEM_ACCESS_USERS_PK" PRIMARY KEY ("USER_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  );
  
  